---
  - name: Fact_Finder
    gather_facts: no
    hosts: csr
    tasks:
      - name: Register Ansible Facts
        setup:
        register: ansible_facts
      - name: Print Ansible Facts
        debug:
          msg: "{{ansible_facts}}"
      - name: Gathering IOS Facts
        vars:
          credentials:
            host: "{{ ansible_host}}"
            username: "{{ username }}"
            password: "{{ password }}"
        ios_facts:
          provider: "{{ credentials }}"
        register: ios_facts_output
      - name: Print IOS Facts
        debug:
          msg: "{{ ios_facts_output }}"
